---
- name: restarts Finder
  ansible.builtin.command: killall Finder

- name: restarts Dock
  ansible.builtin.command: killall Dock

- name: restarts SystemUIServer
  ansible.builtin.command: killall SystemUIServer
