name: CD
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install Ansible
        run: pip install ansible
      - name: Import role to Ansible Galaxy
        run: ansible-galaxy role import --role-name macos_preferences --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }} ayltai ansible-macos-preferences
